import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by Next.js — types use intentional `any` and @ts-ignore
    "src/types/validator.ts",
    "src/types/routes.d.ts",
    // Node.js postinstall scripts — CommonJS require() is intentional here
    "scripts/**",
  ]),
]);

export default eslintConfig;
