import type { Property } from '@/types/property'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: 'Palm Haven Estate',
    location: 'Dubai, UAE',
    price: 2_100_000,
    type: 'villa',
    status: 'available',
    area: 520,
    image: '/images/property-villa.webp',
    tag: 'Luxury',
    units: 8,
    occupiedUnits: 6,
    bedrooms: 5,
    bathrooms: 4,
    parking: 3,
    floor: 0,
    listedDate: '2026-03-12',
    description:
      'A breathtaking estate nestled in the heart of Dubai with panoramic desert views, a private pool, and lush landscaped gardens. The property features world-class finishes, open-plan living spaces, and a dedicated concierge service.',
    amenities: ['Pool', 'Gym', 'Garden', 'Concierge', 'Security', 'Smart Home'],
    agent: { name: 'Layla Hassan', title: 'Luxury Property Specialist', phone: '+971 50 123 4567' },
    activity: [
      { label: 'Property listed', date: '2026-03-12' },
      { label: 'Price adjusted', date: '2026-04-01' },
      { label: 'Viewing scheduled', date: '2026-04-18' },
      { label: 'Offer received', date: '2026-05-02' },
    ],
  },
  {
    id: 'p2',
    title: 'Sky Loft Penthouse',
    location: 'Chicago, IL',
    price: 1_250_000,
    type: 'apartment',
    status: 'available',
    area: 310,
    image: '/images/image.webp',
    tag: 'Featured',
    units: 4,
    occupiedUnits: 3,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    floor: 42,
    listedDate: '2026-02-20',
    description:
      'Iconic penthouse perched on the 42nd floor with floor-to-ceiling windows offering sweeping Chicago skyline and Lake Michigan views. Features a private rooftop terrace, premium appliances, and curated designer interiors.',
    amenities: ['Rooftop', 'Concierge', 'Gym', 'Parking', 'Lounge', 'Security'],
    agent: { name: 'Sarah Chen', title: 'Senior Property Manager', phone: '+1 312 555 0190' },
    activity: [
      { label: 'Property listed', date: '2026-02-20' },
      { label: 'Viewing scheduled', date: '2026-03-05' },
      { label: 'Lease renewed', date: '2026-04-10' },
    ],
  },
  {
    id: 'p3',
    title: 'Maison Sterling',
    location: 'New York, NY',
    price: 1_560_400,
    type: 'house',
    status: 'available',
    area: 338,
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    floor: 0,
    listedDate: '2026-04-05',
    description:
      'An architectural masterpiece in one of Manhattan\'s most sought-after streets. Maison Sterling combines classic New York brownstone charm with contemporary interiors, offering four levels of refined living.',
    amenities: ['Garden', 'Storage', 'Security', 'Smart Home'],
    agent: { name: 'James Wilson', title: 'Real Estate Advisor', phone: '+1 212 555 0177' },
    activity: [
      { label: 'Property listed', date: '2026-04-05' },
      { label: 'Viewing scheduled', date: '2026-04-22' },
    ],
  },
  {
    id: 'p4',
    title: 'Coral Bay Residence',
    location: 'Miami, Florida',
    price: 650_000,
    type: 'townhouse',
    status: 'pending',
    area: 240,
    image: '/images/image.webp',
    units: 3,
    occupiedUnits: 2,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    floor: 1,
    listedDate: '2026-01-18',
    description:
      'A sophisticated waterfront townhouse steps from Biscayne Bay. Enjoy private dock access, resort-style amenities, and a vibrant Miami Beach lifestyle from this stunning three-bedroom residence.',
    amenities: ['Pool', 'Parking', 'Garden', 'Security'],
    agent: { name: 'Marco Santos', title: 'Property Consultant', phone: '+1 305 555 0124' },
    activity: [
      { label: 'Property listed', date: '2026-01-18' },
      { label: 'Offer received', date: '2026-02-14' },
      { label: 'Viewing scheduled', date: '2026-03-09' },
    ],
  },
  {
    id: 'p5',
    title: 'The Pinnacle',
    location: 'San Francisco, CA',
    price: 2_450_000,
    type: 'apartment',
    status: 'available',
    area: 290,
    image: '/images/property-villa.webp',
    tag: 'Premium',
    units: 12,
    occupiedUnits: 9,
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    floor: 38,
    listedDate: '2026-03-28',
    description:
      'Perched atop San Francisco\'s skyline, The Pinnacle offers an unrivalled living experience with sweeping Bay Area views, valet parking, and a five-star building management team. Interiors are curated by an award-winning design studio.',
    amenities: ['Concierge', 'Gym', 'Spa', 'Rooftop', 'Parking', 'Security', 'Lounge'],
    agent: { name: 'Sarah Chen', title: 'Senior Property Manager', phone: '+1 415 555 0211' },
    activity: [
      { label: 'Property listed', date: '2026-03-28' },
      { label: 'Price adjusted', date: '2026-04-15' },
      { label: 'Viewing scheduled', date: '2026-05-10' },
    ],
  },
  {
    id: 'p6',
    title: 'The Orchid Residences',
    location: 'New York, NY',
    price: 520_000,
    type: 'villa',
    status: 'available',
    area: 145,
    image: '/images/image.webp',
    tag: 'New',
    units: 2,
    occupiedUnits: 2,
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floor: 5,
    listedDate: '2026-05-01',
    description:
      'A refined boutique residence in Manhattan\'s Upper East Side, The Orchid Residences deliver an intimate luxury experience with bespoke finishes, private terraces, and seamless access to Central Park.',
    amenities: ['Concierge', 'Garden', 'Security', 'Storage'],
    agent: { name: 'James Wilson', title: 'Real Estate Advisor', phone: '+1 212 555 0177' },
    activity: [
      { label: 'Property listed', date: '2026-05-01' },
    ],
  },
  {
    id: 'p7',
    title: 'Echelon West',
    location: 'Miami, Florida',
    price: 700_500,
    type: 'apartment',
    status: 'pending',
    area: 105,
    units: 6,
    occupiedUnits: 4,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    floor: 14,
    listedDate: '2026-02-08',
    description:
      'A sleek urban apartment in the heart of Brickell, Miami\'s financial district. Echelon West features open layouts, floor-to-ceiling glass, and a resort-style amenity deck with ocean views.',
    amenities: ['Pool', 'Gym', 'Parking', 'Lounge'],
    agent: { name: 'Marco Santos', title: 'Property Consultant', phone: '+1 305 555 0124' },
    activity: [
      { label: 'Property listed', date: '2026-02-08' },
      { label: 'Viewing scheduled', date: '2026-03-20' },
      { label: 'Offer received', date: '2026-04-30' },
    ],
  },
  {
    id: 'p8',
    title: 'Grand Vista Tower',
    location: 'Los Angeles, CA',
    price: 890_000,
    type: 'apartment',
    status: 'rented',
    area: 180,
    image: '/images/image.webp',
    units: 5,
    occupiedUnits: 4,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floor: 22,
    listedDate: '2025-11-15',
    description:
      'Grand Vista Tower occupies a prime West Hollywood location with sweeping views of the Hollywood Hills. The building features a curated selection of modern residences with premium amenities and a vibrant community.',
    amenities: ['Pool', 'Gym', 'Rooftop', 'Concierge', 'Parking'],
    agent: { name: 'Layla Hassan', title: 'Luxury Property Specialist', phone: '+1 310 555 0099' },
    activity: [
      { label: 'Property listed', date: '2025-11-15' },
      { label: 'Lease renewed', date: '2026-01-10' },
      { label: 'Price adjusted', date: '2026-03-01' },
    ],
  },
  {
    id: 'p9',
    title: 'Meridian Heights',
    location: 'Dallas, TX',
    price: 3_200_000,
    type: 'villa',
    status: 'sold-out',
    area: 680,
    image: '/images/property-villa.webp',
    tag: 'Sold',
    units: 4,
    occupiedUnits: 3,
    bedrooms: 6,
    bathrooms: 5,
    parking: 4,
    floor: 0,
    listedDate: '2025-09-20',
    description:
      'The crown jewel of Preston Hollow, Meridian Heights is an extraordinary estate combining classic architecture with cutting-edge smart-home technology, a championship tennis court, and a resort-style pool complex.',
    amenities: ['Pool', 'Gym', 'Garden', 'Spa', 'Tennis', 'Smart Home', 'Security', 'Storage'],
    agent: { name: 'Sarah Chen', title: 'Senior Property Manager', phone: '+1 214 555 0322' },
    activity: [
      { label: 'Property listed', date: '2025-09-20' },
      { label: 'Offer received', date: '2025-10-18' },
      { label: 'Price adjusted', date: '2025-11-05' },
      { label: 'Lease renewed', date: '2026-02-20' },
    ],
  },
  {
    id: 'p10',
    title: 'The Bristol',
    location: 'Boston, MA',
    price: 940_000,
    type: 'office',
    status: 'available',
    area: 220,
    listedDate: '2026-04-14',
    description:
      'A premium commercial space in Boston\'s financial district, The Bristol provides a best-in-class work environment with high ceilings, natural light, and a full suite of corporate amenities.',
    amenities: ['Parking', 'Lounge', 'Security', 'Storage', 'Concierge'],
    agent: { name: 'James Wilson', title: 'Real Estate Advisor', phone: '+1 617 555 0288' },
    activity: [
      { label: 'Property listed', date: '2026-04-14' },
      { label: 'Viewing scheduled', date: '2026-05-08' },
    ],
  },
  {
    id: 'p11',
    title: 'Willow Creek Estate',
    location: 'Austin, TX',
    price: 1_875_000,
    type: 'house',
    status: 'rented',
    area: 445,
    image: '/images/image.webp',
    bedrooms: 4,
    bathrooms: 3,
    parking: 3,
    floor: 0,
    listedDate: '2025-12-01',
    description:
      'Tucked along a serene creek in Austin\'s most coveted neighbourhood, Willow Creek Estate offers four acres of private grounds, a chef\'s kitchen, and an entertainer\'s dream backyard with a heated pool and outdoor kitchen.',
    amenities: ['Pool', 'Garden', 'Smart Home', 'Security', 'Storage', 'Gym'],
    agent: { name: 'Marco Santos', title: 'Property Consultant', phone: '+1 512 555 0456' },
    activity: [
      { label: 'Property listed', date: '2025-12-01' },
      { label: 'Lease renewed', date: '2026-02-28' },
    ],
  },
  {
    id: 'p12',
    title: 'Harbor Point Loft',
    location: 'Seattle, WA',
    price: 480_000,
    type: 'apartment',
    status: 'pending',
    area: 165,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    floor: 8,
    listedDate: '2026-03-03',
    description:
      'A beautifully converted industrial loft in Seattle\'s South Lake Union district, featuring exposed brick, soaring ceilings, and stunning Puget Sound views. Steps from Pike Place Market and the city\'s finest dining.',
    amenities: ['Gym', 'Parking', 'Lounge', 'Storage'],
    agent: { name: 'Layla Hassan', title: 'Luxury Property Specialist', phone: '+1 206 555 0178' },
    activity: [
      { label: 'Property listed', date: '2026-03-03' },
      { label: 'Viewing scheduled', date: '2026-04-12' },
      { label: 'Offer received', date: '2026-05-15' },
    ],
  },
]
